In [6]:
# Assignment Numpy

# Problem Statement 1:

# Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically,
# when increasing is False, the i-th output column is the input vector raised element-wise
# to the power of N - i - 1.
# HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [13]:
# Creating a function that gives powers based on the input vector(N)

import numpy as np
x=np.array([1,2,3,4])
N=4
function1=np.column_stack([x**(N-i-1) for i in range (N)])
print(function1)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [14]:
# A simlar function can be created using np.vander in numpy

import numpy as np
x=np.array([1,2,3,4])
N=4
function2=np.vander(x,N,increasing=False)
print(function2)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [15]:
# The determitant for both functions will be the same

np.linalg.det(function1)

11.99999999999999

In [16]:
np.linalg.det(function2)

11.99999999999999

In [17]:
# Problem Statement 2:

# Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving
# average of the given sequence is defined as follows:
# The moving average sequence has n-k+1 elements as shown below.
# The moving averages with k=4 of a ten-value sequence (n=10) is shown below
# i 1 2 3 4 5 6 7 8 9 10
# ===== == == == == == == == == == ==
# Input 10 20 30 40 50 60 70 80 90 100
# y1 25 = (10+20+30+40)/4
# y2 35 = (20+30+40+50)/4
# y3 45 = (30+40+50+60)/4
# y4 55 = (40+50+60+70)/4
# y5 65 = (50+60+70+80)/4
# y6 75 = (60+70+80+90)/4
# y7 85 = (70+80+90+100)/4
# Thus, the moving average sequence has n-k+1=10-4+1=7 values.

#Question: Write a function to find moving average in an array over a window:
# Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3

# Here is the function to find moving average in an array:
# We'll use np.cumsum to get the cumulative sum of the given numbers
# We'll break the array per 'n' and subtract elements to get the results

import numpy as np
def moving_average(a,n=3):
    asum=np.cumsum(a,dtype=float)
    asum[n:]=asum[n:]-asum[:-n]
    return asum[n-1:]/n

In [18]:
a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
a1=np.array(a)

# Restricting the decimals to only 2 digits

np.array(moving_average(a1,n=3)).round(2)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])